-- Model Registry bootstrap for the NVIDIA-only router.
-- Model IDs live in data, not Vercel environment variables or application routing code.
-- Only records that passed the project's current provider/origin/privacy review are production enabled.

insert into public.model_registry (
  provider,
  model_id,
  enabled,
  developer_company,
  country_of_headquarters,
  china_origin_excluded,
  origin_reviewed_at,
  approved_provider,
  approved_model,
  allowed_for_student_data,
  training_on_api_data,
  zero_data_retention_available,
  security_review_passed,
  security_reviewed_at,
  privacy_policy_verified,
  privacy_reviewed_at,
  deprecated,
  capabilities_json,
  evaluation_profile_json,
  production_approved,
  updated_at
)
values
  (
    'nvidia',
    'nvidia/nemotron-3-nano-30b-a3b',
    true,
    'NVIDIA Corporation',
    'United States',
    true,
    now(),
    true,
    true,
    true,
    false,
    false,
    true,
    now(),
    true,
    now(),
    false,
    '{"korean":true,"reasoning":true,"structured_output":true,"long_context":true}'::jsonb,
    '{"qualityTier":"efficient","priority":80,"taskAffinity":["task_parser"],"dataPolicy":"deidentified_non_sensitive_student_content_only","reviewBasis":"NVIDIA model card + current API Trial Terms"}'::jsonb,
    true,
    now()
  ),
  (
    'nvidia',
    'nvidia/nemotron-3-super-120b-a12b',
    true,
    'NVIDIA Corporation',
    'United States',
    true,
    now(),
    true,
    true,
    true,
    false,
    false,
    true,
    now(),
    true,
    now(),
    false,
    '{"korean":true,"reasoning":true,"structured_output":true,"long_context":true}'::jsonb,
    '{"qualityTier":"high","priority":90,"taskAffinity":["strategy","writer","logic_critic","curriculum_verifier","rubric_grader","final_rewriter"],"dataPolicy":"deidentified_non_sensitive_student_content_only","reviewBasis":"NVIDIA model card + current API Trial Terms"}'::jsonb,
    true,
    now()
  ),
  (
    'nvidia',
    'nvidia/nemotron-3.5-lightning-30b-a3b',
    false,
    'NVIDIA Corporation',
    'United States',
    true,
    now(),
    true,
    false,
    false,
    false,
    false,
    true,
    now(),
    true,
    now(),
    false,
    '{"korean":false,"reasoning":true,"structured_output":false,"long_context":true}'::jsonb,
    '{"qualityTier":"efficient","priority":0,"taskAffinity":[],"status":"candidate_requires_internal_eval","reviewBasis":"NVIDIA catalog candidate; production approval intentionally withheld"}'::jsonb,
    false,
    now()
  )
on conflict (model_id) do update set
  provider = excluded.provider,
  enabled = excluded.enabled,
  developer_company = excluded.developer_company,
  country_of_headquarters = excluded.country_of_headquarters,
  china_origin_excluded = excluded.china_origin_excluded,
  origin_reviewed_at = excluded.origin_reviewed_at,
  approved_provider = excluded.approved_provider,
  approved_model = excluded.approved_model,
  allowed_for_student_data = excluded.allowed_for_student_data,
  training_on_api_data = excluded.training_on_api_data,
  zero_data_retention_available = excluded.zero_data_retention_available,
  security_review_passed = excluded.security_review_passed,
  security_reviewed_at = excluded.security_reviewed_at,
  privacy_policy_verified = excluded.privacy_policy_verified,
  privacy_reviewed_at = excluded.privacy_reviewed_at,
  deprecated = excluded.deprecated,
  capabilities_json = excluded.capabilities_json,
  evaluation_profile_json = excluded.evaluation_profile_json,
  production_approved = excluded.production_approved,
  updated_at = excluded.updated_at;
